### ISSUE TITLE
Cyrillic encoded by cheerio

### ISSUE THREAD

**Issue by vitaliy-bobrov** [astralfrontier/metalsmith-open-graph#8]
I had an issue that all cyrillic symbols was encoded, I did a hard exploration and found that cheerio encodes it. As you pass all options to cheerio it is possible to fix it ny passing `decodeEntities: false` to options. May be it should be mentioned in docs, because not so easy to find solution :)
Also see: https://github.com/cheeriojs/cheerio/issues/711

**Comment by astralfrontier** [comment]
Do you think this should be a default value, or is documenting it good enough?

**Comment by vitaliy-bobrov** [comment]
I think documenting will be enough for now.
